apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: postgres
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
