apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: aurora
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
    - name: management
      port: 15672
      targetPort: 15672
      protocol: TCP

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: aurora
spec:
  serviceName: rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.9.11-management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672